// features/specialist/__mocks__/mockProfileData.ts
import { SpecialistMock } from '../types';

const mockProfileData: SpecialistMock = {
  id: 'spc12345',
  name: 'Ігор Литвин',
  avatar: '/images/specy/ihor-lytvyn-2.jpg',
  joinDate: '2022-03-09', 
  icon: 'icon-verified',
  iconDog: 'icon-spec-dog',
  iconCat: 'icon-cat',
  iconRight: 'icon-arrow-right',
  iconLeft: 'icon-arrow-left',
  iconBottom: 'icon-arrow-bottom',
  profession: 'Перетримка / Догляд вдома',
  rating: 4.8,
  reviewsCount: 56,
  experience: '3 роки',
  location: 'Київ, Україна',
  online: true,
  bio: 'Про себе: Я Ігор, живу в приватному будинку з великим огородженим двором. Приймаю собак будь-якого розміру на перетримку. Є зона для вигулу, місце для ігор і, головне — любов до тварин. Проживаю в районі Академмістечка, проте також маю можливість виїзду до вас додому, де буду здійснювати догляд за вашим улюбленцем.',
  services: [
    {
      id: 'dog-srv1',
      type: 'dog',
      title: 'Догляд дома',
      duration: 'грн/год',
      price: 250,
      currency: '₴',
    },
    {
      id: 'dog-srv2',
      type: 'dog',
      title: 'Перетримка',
      duration: 'грн/доба',
      price: 450,
      currency: '₴',
    },
    {
      id: 'dog-srv3',
      type: 'dog',
      title: 'Грумінг',
      duration: 'грн/тушка',
      price: 350,
      currency: '₴',
    },
    {
      id: 'dog-srv4',
      type: 'dog',
      title: 'Вигулювання',
      duration: 'грн/год',
      price: 150,
      currency: '₴',
    },
    {
      id: 'cat-srv1',
      type: 'cat',
      title: 'Догляд дома',
      duration: 'грн/год',
      price: 200,
      currency: '₴',
    },
    {
      id: 'cat-srv2',
      type: 'cat',
      title: 'Перетримка',
      duration: 'грн/доба',
      price: 350,
      currency: '₴',
    },
    {
      id: 'cat-srv3',
      type: 'cat',
      title: 'Грумінг',
      duration: 'грн/тушка',
      price: 250,
      currency: '₴',
    },
    {
      id: 'cat-srv4',
      type: 'cat',
      title: 'Вигулювання',
      duration: 'грн/год',
      price: 100,
      currency: '₴',
    },
  ],
  specializations: ['Собаки', 'Коти', 'Перетримка', 'Догляд вдома'],
  education: [
    {
      institution: 'КНУ ім. Т. Шевченка',
      degree: 'Магістр психології',
      year: 2015,
    },
  ],
  languages: ['Українська', 'Російська', 'Англійська'],
  availableDays: ['Понеділок', 'Середа', 'П’ятниця'],
  isVerified: true,
  contact: {
    email: 'ihor@example.com',
    phone: '+380961234567',
    website: 'https://pet-help.com.ua',
  },

  petsPhotos: [
    '/images/loveAnimal/1.jpg',
    '/images/loveAnimal/2.jpg',
    '/images/loveAnimal/3.jpg',
    '/images/loveAnimal/4.jpg',
    '/images/loveAnimal/2.jpg',
    '/images/loveAnimal/3.jpg',
    '/images/loveAnimal/4.jpg',
    '/images/loveAnimal/2.jpg',
    '/images/loveAnimal/3.jpg',
    '/images/loveAnimal/4.jpg',
    '/images/loveAnimal/1.jpg',
  ], 
};

export default mockProfileData;